export const INITIAL_COMPANIES = [
  {
    id: '1', name: 'Amazon Flex', website: 'flex.amazon.com',
    mainPhone: '1-888-281-6901', activeStates: ['ALL_50'],
    workModel: ['App / On Demand','Route'], serviceType: ['Package Delivery','Delivery Route','Medical / Rx'],
    vehicles: ['Car','SUV','Minivan'], status: 'Waiting', priority: 'High',
    handler: 'King Solomon', followUp: '2026-03-28', signupUrl: 'flex.amazon.com',
    notes: '3-6 hr blocks. Prime, Whole Foods, and pharmacy routing. $18-25/hr. Escalade qualifies for larger blocks.',
    contactName: 'John Martinez', contactTitle: 'Regional Manager',
    contactEmail: 'john.m@amazonflex.io', contactPhone: '+1 (206) 555-0147',
    contactLinkedin: 'linkedin.com/in/jmartinez', contactMethod: 'LinkedIn',
    vehicleOther: '', serviceOther: '', color: '#2E75B6',
    createdAt: '2026-03-01', lastModified: '2026-03-13',
  },
  {
    id: '2', name: 'DoorDash', website: 'dasher.doordash.com',
    mainPhone: '1-855-973-1040', activeStates: ['ALL_50'],
    workModel: ['App / On Demand'], serviceType: ['Food Delivery','Catering','Delivery Route'],
    vehicles: ['Car','Bike / Scooter'], status: 'Active', priority: 'High',
    handler: 'King Solomon', followUp: '', signupUrl: 'dasher.doordash.com',
    notes: 'Largest US food platform. Catering orders unlock at higher driver levels.',
    contactName: '', contactTitle: '', contactEmail: '', contactPhone: '',
    contactLinkedin: '', contactMethod: 'Email',
    vehicleOther: '', serviceOther: '', color: '#C0392B',
    createdAt: '2026-01-15', lastModified: '2026-03-10',
  },
  {
    id: '3', name: 'Curri', website: 'curri.com/drive',
    mainPhone: '1-888-252-8774', activeStates: ['ALL_50'],
    workModel: ['App / On Demand','Route','Fleet'], serviceType: ['Construction','Package Delivery','Delivery Route'],
    vehicles: ['Car','Pickup Truck','SUV','Cargo Van','Box Truck'], status: 'Researching', priority: 'High',
    handler: 'King Solomon', followUp: '2026-03-30', signupUrl: 'curri.com/drive',
    notes: '$50/hr avg. Construction and industrial materials. Escalade perfect fit.',
    contactName: '', contactTitle: 'Driver Relations', contactEmail: 'drivers@curri.com',
    contactPhone: '1-888-252-8774', contactLinkedin: '', contactMethod: 'Email',
    vehicleOther: '', serviceOther: '', color: '#E65100',
    createdAt: '2026-03-01', lastModified: '2026-03-12',
  },
  {
    id: '4', name: 'Favor', website: 'favordelivery.com',
    mainPhone: '1-512-717-0000', activeStates: ['TX'],
    workModel: ['App / On Demand'], serviceType: ['Food Delivery'],
    vehicles: ['Car','Bike / Scooter'], status: 'Active', priority: 'High',
    handler: 'Sarah', followUp: '', signupUrl: 'favordelivery.com/runner-application',
    notes: 'Texas-based. Very strong DFW presence. Best local food delivery option for TX.',
    contactName: '', contactTitle: '', contactEmail: '', contactPhone: '',
    contactLinkedin: '', contactMethod: 'Email',
    vehicleOther: '', serviceOther: '', color: '#7B3F9E',
    createdAt: '2026-01-10', lastModified: '2026-03-05',
  },
  {
    id: '5', name: 'GoShare', website: 'goshare.co/drivers',
    mainPhone: '1-844-467-4673', activeStates: ['TX','CA','FL','GA','OH'],
    workModel: ['App / On Demand','Fleet'], serviceType: ['Package Delivery','Construction','Delivery Route'],
    vehicles: ['Pickup Truck','Cargo Van','Box Truck','SUV'], status: 'Researching', priority: 'High',
    handler: 'King Solomon', followUp: '2026-03-29', signupUrl: 'goshare.co/drivers',
    notes: 'Avg $45+/hr. Deloitte Fast 500 2025. Great for Escalade.',
    contactName: '', contactTitle: '', contactEmail: '', contactPhone: '',
    contactLinkedin: '', contactMethod: 'Email',
    vehicleOther: '', serviceOther: '', color: '#1B7A35',
    createdAt: '2026-03-01', lastModified: '2026-03-20',
  },
  {
    id: '6', name: 'DeliverThat', website: 'ideliverthat.com/driver',
    mainPhone: '1-844-335-4828', activeStates: ['ALL_50'],
    workModel: ['App / On Demand','Route'], serviceType: ['Catering','Delivery Route'],
    vehicles: ['Car','SUV','Cargo Van','Box Truck'], status: 'Waiting', priority: 'High',
    handler: 'King Solomon', followUp: '2026-03-29', signupUrl: 'ideliverthat.com/driver',
    notes: '$30-45 per delivery. 9am-2pm typical hours. Escalade perfect fit.',
    contactName: '', contactTitle: '', contactEmail: 'drivers@deliverthat.com',
    contactPhone: '', contactLinkedin: '', contactMethod: 'Email',
    vehicleOther: '', serviceOther: '', color: '#2563b8',
    createdAt: '2026-03-01', lastModified: '2026-03-08',
  },
  {
    id: '7', name: 'Uber XL', website: 'uber.com/us/en/drive',
    mainPhone: '1-800-868-2489', activeStates: ['ALL_50'],
    workModel: ['App / On Demand'], serviceType: ['Rideshare','Senior Services'],
    vehicles: ['SUV','Luxury/Black Car'], status: 'Active', priority: 'High',
    handler: 'King Solomon', followUp: '', signupUrl: 'uber.com/us/en/drive',
    notes: 'Active Uber XL. Escalade qualifies. Premium per-ride rate.',
    contactName: '', contactTitle: '', contactEmail: '', contactPhone: '',
    contactLinkedin: '', contactMethod: 'Phone',
    vehicleOther: '', serviceOther: '', color: '#1A1A1A',
    createdAt: '2026-01-01', lastModified: '2026-02-28',
  },
  {
    id: '8', name: 'Spark Driver', website: 'sparkdriverapp.com',
    mainPhone: '1-800-966-6546', activeStates: ['ALL_50'],
    workModel: ['App / On Demand','Route'], serviceType: ['Grocery Delivery','Package Delivery','Delivery Route'],
    vehicles: ['Car','SUV','Minivan','Cargo Van'], status: 'Active', priority: 'High',
    handler: 'King Solomon', followUp: '', signupUrl: 'sparkdriverapp.com',
    notes: 'Walmart delivery. DFW zones open. All 50 states. Shop and deliver.',
    contactName: '', contactTitle: '', contactEmail: '', contactPhone: '',
    contactLinkedin: '', contactMethod: 'Email',
    vehicleOther: '', serviceOther: '', color: '#0071CE',
    createdAt: '2026-01-15', lastModified: '2026-02-20',
  },
];

export const INITIAL_ACTIVITIES = [
  {
    id: 'a1', companyId: '1', companyName: 'Amazon Flex',
    type: 'Phone', outcome: 'Interested', handler: 'King Solomon',
    dateTime: 'Mar 13, 2026 at 6:00 AM',
    notes: "John said they're expanding DFW routes. Very positive. Will send contract details.",
    nextAction: 'Call on Mar 14, 2026',
  },
  {
    id: 'a2', companyId: '1', companyName: 'Amazon Flex',
    type: 'Email', outcome: 'Pending', handler: 'King Solomon',
    dateTime: 'Mar 8, 2026 at 9:30 AM',
    notes: 'Sent initial inquiry email with availability and vehicle details.',
    nextAction: 'Call on Mar 12, 2026',
  },
  {
    id: 'a3', companyId: '5', companyName: 'GoShare',
    type: 'Email', outcome: 'Pending', handler: 'Sarah',
    dateTime: 'Mar 20, 2026 at 2:00 PM',
    notes: 'Submitted application with vehicle photos. Awaiting vehicle inspection.',
    nextAction: 'Follow up Mar 27',
  },
];

export const INITIAL_HANDLERS = ['King Solomon', 'Sarah', 'Unassigned'];
